### ISSUE TITLE
Please remove FutureWarning when importing uproot3 (for now)

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/uproot3#533]
uproot3 raises a Warning when you import it, please remove this warning.

Currently there is no way to drop uproot3, because uproot4 cannot write files. Since it is impossible to port all code to uproot4, it is safe to assume that a user who does `import uproot3` does so *intentionally*. It then does not make sense to warn that user that this package is deprecated.

I suggest to hold back on the warning until uproot4 can really replace uproot3 completely. Then reinstate it.

**Comment by tamasgal** [comment]
Just a side-note, meanwhile you can go with the snipped below, but I also think that `import uproot3` is intentional enough `:)`

```python
import warnings
with warnings.catch_warnings():
    warnings.simplefilter("ignore", category=FutureWarning)
    import uproot3
```

**Comment by jpivarski** [comment]
Okay, you've convinced me. I think those warnings were put there before the name change, encouraging people to opt into the new versions when it still had to be done intentionally (and then the names were changed in the warning message without removing the warning message). But it does make sense that if someone has gone out of their way to `pip install uproot3` and then `import uproot3`, they know about the existence of Uproot 4.

There are new versions of `uproot3` and `awkward0` in PyPI without warnings (`uproot3-methods` didn't have a warning).
